name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact
        path: /home/runner/work/Techmino-autoupdater/Techmino-autoupdater/target/release/
        if-no-files-found: warn
        retention-days: 90
