name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      run: cargo build --release --verbose
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: /home/runner/work/Techmino-autoupdater/Techmino-autoupdater/target/release/techmino-autoupdater
        if-no-files-found: warn
        retention-days: 90

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-msvc
        override: true
    - name: Build Windows
      env:
        CARGO_TARGET_DIR: ./target
      run: cargo build --release --target x86_64-pc-windows-msvc --verbose
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: target/x86_64-pc-windows-msvc/release/techmino-autoupdater.exe
        if-no-files-found: warn
        retention-days: 90
